Adding elements to manage the new data mart database

diff --git a/templates/db_worker/application.erb b/templates/db_worker/application.erb
--- a/templates/db_worker/application.erb
+++ b/templates/db_worker/application.erb
@@ -33,6 +33,7 @@ LOGGER="logger -t ${INSTANCE_NAME} -p daemon.info"
 
 $LOGGER "Running SQL fixture..."
 
+# Check that psql command line client is available, fail if not
 PSQL=$(which psql)
 
 if [ ! -x "$PSQL" ]; then
@@ -40,12 +41,22 @@ if [ ! -x "$PSQL" ]; then
   exit 1
 fi
 
+# Check that psql command line client is available, fail if not
+FLYWAY=$(which flyway)
+
+if [ ! -x "FLYWAY" ]; then
+$LOGGER 'Unable to find flyway executable, exiting!'
+exit 1
+fi
+
 DB_USER=<%= checkEnv('LEEROY_DB_USER') %>
 DB_NAME=<%= checkEnv('LEEROY_DB_NAME') %>
 DB_HOST=<%= getRDSInstanceEndpoint(checkEnv('LEEROY_DB_HOST')) %>
 DB_PASSWORD=<%= checkEnv('LEEROY_DB_PASSWORD') %>
+DB_APP_USER=<%= checkEnv('LEEROY_DB_APP_USER') %>
 
 DB_FILE=fixture.sql
+DB_TARBALL=fixtures.tar.gz
 DB_LOG="${DB_NAME}.log"
 
 # read SQL file from S3
@@ -53,6 +64,25 @@ $AWS s3 cp "s3://rk-devops-${REGION}/jenkins/fixtures/sql/${DB_NAME}.sql" $DB_FI
 
 # run SQL file against database
 PGPASSWORD="$DB_PASSWORD" $PSQL -h $DB_HOST -U $DB_USER -f $DB_FILE -d postgres > $DB_LOG
+
+# retrieve flyway database scripts from S3
+$AWS s3 cp "s3://rk-devops-${REGION}/jenkins/fixtures/sql/datamart-<%= checkEnv('LEEROY_BRANCH') %>.tar.gz" $DB_TARBALL
+tar zxf $DB_TARBALL
+cd fixtures
+
+# create flyway config file
+cat > flyway.conf <<"FLYWAY_CONF"
+flyway.url=jdbc:postgresql://${DB_HOST}/datamart
+flyway.user=$DB_USER
+flyway.password=$DB_PASSWORD
+flyway.locations=filesystem:.
+flyway.placeholders.appUser=$DB_APP_USER # TODO: Pass in app user from leeroy
+flyway.placeholders.etlUser=$DB_APP_USER
+FLYWAY_CONF
+
+$FLYWAY clean >> $DB_LOG
+
+$FLYWAY migrate >> $DB_LOG
 
 # copy log to S3
 $AWS s3 cp $DB_LOG "s3://rk-devops-${REGION}/jenkins/logs/${DB_LOG}"
